### PR TITLE
Makefile refactoring and Travis CI integration

### PR DESCRIPTION
**Pull request by JaCzekanski**
Hello,
I have cleaned Makefile to allow simple 
> make

command to build project without modifying any files. 
By default it builds Raspberry Pi 3 version, it can be overriden like this
> make RASPPI=0

I had to edit few files because they were using \ instead of / in includes and used invalid cases in filenames (works on Windows, not so much on Linux).

All versions can be built, but I only tested ones for RPI 3 and RPI Zero - both are booting correctly, usb and hdmi works. I don't have right hardware to test communication with C64, but will do it this week.

Last thing I did is integration with Travis CI ([example build](https://travis-ci.org/JaCzekanski/Pi1541/builds/381469179)) to automatically build all versions - it will allow to deploy all binaries on git tag to GitHub Releases or different provider.

I think it would be a cool idea to create zip with RPI firmware and 1541 rom attached to simplify whole process for new users.

### CODE REVIEW

**Comment by penfold42** [comment]
Does it build on linux ?

I’ve been doing similar mods on my fork - I just got it to successfully build 10 mins ago but haven’t tried booting it yet

**Comment by JaCzekanski** [comment]
@penfold42 Yes, in fact Travis builds are using Linux and it works fine.

**Comment by penfold42** [comment]
Compiled and runs fine on on my pi3 with real hardware.

It doesn’t compile when doing a pi2 build with linker errors

**Comment by JaCzekanski** [comment]
@penfold42 Which GCC version are you using?
On CI I'm using this toolchain: https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads/5-2016-q2-update

And locally I'm using this version:
> λ arm-none-eabi-gcc --version
> arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 5.4.1 20160609 (release)

**Comment by penfold42** [comment]
Lots of these - probably one for each object its trying to link:
```
/usr/lib/gcc/arm-none-eabi/5.4.1/../../../arm-none-eabi/bin/ld: error: kernel.elf uses VFP register arguments, /usr/lib/gcc/arm-none-eabi/5.4.1/../../../arm-none-eabi/lib/libc.a(lib_a-wctomb_r.o) does not
/usr/lib/gcc/arm-none-eabi/5.4.1/../../../arm-none-eabi/bin/ld: failed to merge target specific data of file /usr/lib/gcc/arm-none-eabi/5.4.1/../../../arm-none-eabi/lib/libc.a(lib_a-wctomb_r.o)
collect2: error: ld returned 1 exit status
Makefile:18: recipe for target 'kernel' failed
```

```
arm-none-eabi-gcc --version
arm-none-eabi-gcc (15:5.4.1+svn241155-1) 5.4.1 20160919
```

and the dpkg -l of the related packages:
```
 binutils-arm-none-eabi               2.28-5+9+b3
 gcc-arm-none-eabi                    15:5.4.1+svn241155-1
 libnewlib-arm-none-eabi              2.4.0.20160527-2
 libstdc++-arm-none-eabi-newlib       15:5.4.1+svn241155-1+9
```

**Comment by penfold42** [comment]
Should we move the code into a src/ folder ?

Then we can add docs/ hardware/

**Comment by JaCzekanski** [comment]
@penfold42 GCC is not using fpu version of libc.a - I had exact same problem. I changed -march paramterer but it looks like it didin't solve the problem completely. I will take a look at it later.

I wanted to move sources to different directory but I'd like to make sure that author is OK with that.

**Comment by JaCzekanski** [comment]
@penfold42 I have changed mfpu to **crypto-neon-fp-armv8** for RPI3 - check if this fixes build on your machine.

I also have moved sources do src/ making structure more readable.

**Comment by JaCzekanski** [comment]
I have built converter level and connected my Raspberrys to C64.
RPI3 - work great.
RPI0 - C64 detects drive, LOAD"$",8 works correctly, but selecting D64 on Pi1541 and loading any file from it ("$" or "*") hangs c64. 

Looking at the source code I assume that Zero is too slow for current emulation code. 
Not sure if multiple cores are required - from what I see only second core is used to display realtime graph of IEC communication.

**Comment by pi1541** [comment]
Hi guys. Thanks for the help. Great work cleaning up my mess! (sorry about that)

RPI0 is not working as it cannot keep 1us timings when in emulation mode.
I have experimented with RPI0. I pegged everything back (ie no USB, no interrupts) and even overclocked to 1.2GHz it still can't keep timings. I can underclock a RPI3 to just over 1GHz and it can keep timings, weird.

Does anyone know how to turn off the governor to remove the need to have "force_turbo=1" in the config.txt? Why does a PI3 need the governor turned off anyway?

**Comment by JaCzekanski** [comment]
@pi1541
Could you connect this account with Travis CI and enable builds for this project?
Steps 1-2 from this [guide](https://docs.travis-ci.com/user/getting-started/)

**Comment by pi1541** [comment]
Hi Jakub

I think I did it correctly.

**Pull request merged**
